spring:
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
    clean-disabled: true
  datasource:
    url: jdbc:mysql://192.168.100.80:3306/app?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      pool-name: app-pool
      maximum-pool-size: 25
      max-lifetime: 150000
      validation-timeout: 1000
      minimum-idle: 20
  redis:
    host: 192.168.100.80
    port: 6379
    timeout: 1000
    lettuce:
      pool:
        min-idle: 5
        max-active: 8
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.100.80:8080

logging:
  config: classpath:logback.xml

mybatis-plus:
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mybatis/**/*.xml

# 自定义配置
vcloud:
  swagger: true
  skip-urls:
    - /auth/oauth/**
    - /**/swagger*/**
    - /**/v3/**
  auth-key:
    - appid: sysWeb
      secret: 6842224b-7ddb-4c63-af62-1db58d77b2a5
    - appid: app
      secret: a135ec07-6eb2-4300-840a-9977dd8c813c
  cache:
    - cache-name: user
      ttl: 1800000
      max-idle-time: 1200000