spring:
  datasource:
    url: jdbc:mysql://192.168.100.80:3306/app?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      pool-name: vcloud
      maximum-pool-size: 25
      max-lifetime: 1500000
      validation-timeout: 1000
      minimum-idle: 20
  redis:
    host: 192.168.100.80
    port: 6379
    connect-timeout: 1000
    timeout: 1000
    lettuce:
      pool:
        min-idle: 5
        max-active: 8
  jpa:
    open-in-view: false
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
    clean-disabled: true
  jackson:
    default-property-inclusion: non_empty
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.100.80
        port: 8719
logging:
  config: classpath:logback.xml
mybatis-plus:
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mybatis/**/*.xml

# 自定义配置
vcloud:
  swagger: true
  skip-urls:
    - /auth/**
    - /**/swagger*/**
    - /**/v3/**
  authorization-urls:
    - /admin/**
  auth-key:
    - app-id: web
      secret: 6842224b-7ddb-4c63-af62-1db58d77b2a5
      platform: 0
      public-key: |-
        -----BEGIN PUBLIC KEY-----
        MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAmwU8KJMgMDNSnmlYLfGE
        CbpECbS9qcmCQgMXWbeK1dae3xnbVNtIsN/Hsdr9q8wT8qzynGw739ijp/is1Wcf
        HqFn3diuurZQSIQHN1pLz7pxISKYzjY+e0j1ELsGkGdb04fqsPGJnh/TEzcVMeHD
        xGT8+9XZkp3Ub3ZyZ6bqwNVwr1eTR4L2FGMmEBq5CXTd2HOH/nfKiz8+kOv02DTW
        JmNSPTGEzpG7gwWeZFsRLipHaoNq0n4xoHCUGGM9gzgzgjAVVdwlVKkej+NiSKcq
        JfxRvjzaI9+y6TCxfJ/zs7ccUJljeckrVz4iktGzxfBm+JenNTYx74E4jT0Bg28o
        Tn7QeTCK6Hog9Ro/ow8ceU/K8Yrn7p2FqKbwPViKVEu66MosJ09O+Cogj9NanKO5
        Qh6ip08/dtxl+ln2sSJOA1LNcKZA0hbhSkIIF9P0Q8rUNWka1peZqSOQk0SFLB3s
        Htvv1dsbi3hY5zBNdG6X09bbylMwdasSVplurOYBubCSrcT3dbenjmoqBLCZzOlx
        o9IydVKKo8y+0KZ9FTgn+T6WQxNCKrp7tbKWlAkHzio06+BDZ6uFOwzUm+Ur9RtZ
        QvipaGtEQoEaw+h7AP50WQs6OrBPh7HeVp728CJOaXk4kkHmSfIrmQsr9BunWtX1
        Y8wDuSslUuP0CfVwlStT5EcCAwEAAQ==
        -----END PUBLIC KEY-----
      private-key: |-
        -----BEGIN PRIVATE KEY-----
        MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQCbBTwokyAwM1Ke
        aVgt8YQJukQJtL2pyYJCAxdZt4rV1p7fGdtU20iw38ex2v2rzBPyrPKcbDvf2KOn
        +KzVZx8eoWfd2K66tlBIhAc3WkvPunEhIpjONj57SPUQuwaQZ1vTh+qw8YmeH9MT
        NxUx4cPEZPz71dmSndRvdnJnpurA1XCvV5NHgvYUYyYQGrkJdN3Yc4f+d8qLPz6Q
        6/TYNNYmY1I9MYTOkbuDBZ5kWxEuKkdqg2rSfjGgcJQYYz2DODOCMBVV3CVUqR6P
        42JIpyol/FG+PNoj37LpMLF8n/OztxxQmWN5yStXPiKS0bPF8Gb4l6c1NjHvgTiN
        PQGDbyhOftB5MIroeiD1Gj+jDxx5T8rxiufunYWopvA9WIpUS7royiwnT074KiCP
        01qco7lCHqKnTz923GX6WfaxIk4DUs1wpkDSFuFKQggX0/RDytQ1aRrWl5mpI5CT
        RIUsHewe2+/V2xuLeFjnME10bpfT1tvKUzB1qxJWmW6s5gG5sJKtxPd1t6eOaioE
        sJnM6XGj0jJ1UoqjzL7Qpn0VOCf5PpZDE0Iqunu1spaUCQfOKjTr4ENnq4U7DNSb
        5Sv1G1lC+Kloa0RCgRrD6HsA/nRZCzo6sE+Hsd5WnvbwIk5peTiSQeZJ8iuZCyv0
        G6da1fVjzAO5KyVS4/QJ9XCVK1PkRwIDAQABAoICAAM1HIWKZcQZi8ATVeu9b4nz
        /KxmvPXiYXuULMuCbLD3+9mJ42viDaL7PlqDuXPwiQkgYvSxmJuNE/XJw2m29IHh
        vRBuB099rjOR58RRbfgiV2zkFl1N6gULAWcTN5ONT+0UhtqaZMqMxgVDwoCBt1c8
        768WQaYy9c5ImR1j6r+KqwY1vaphH05UrtjudJ2peV2dJlcxi1NOP7En8Kz4iuXI
        cE8r0x+jDEott5VD/RsDbO7bQT6Rtd0n9yh6BS/N3eL3s7lPEMarqSI5BjOSoeCf
        U+GnyKutWTpR85oshRJW25MfWVuPugHYG0cGZ73Ut4y1NpR3Rpk6Bz2E4Z8ikabl
        4QPTU+PI9W7ComIGlC77NmL5FhosTRe7m4T4emwXVZZLQZKNc0fvbUm4aqbiNwZy
        rikrlKfbbLAxzeudYNGodBceAP0OLkfGTrGVN/U4NFje3q9slUIP0OefckWiKDOR
        5+jGt8f7OsVfTogktOZzs+H3JKiNemN9QE7PJsXqeBlYfh8kwplNAmFZFt0EQWVg
        rMzO0U4/rGbf98HJ16O5iwkKLQ8zhQVz695enlWINkd4hc0BfLqVigCvUzS6kzk8
        ZHq4Eyo91Gn1y1A1q4DW6+uM28WvDCsUn96IORQGJGf9N+anFtnRYJI3jTV6GdYW
        GfFZZiRz3rWBSF8K5UbhAoIBAQDOoIcHWQZydJFAXiycM371sUJ+xx4EUYD0RGzg
        1RFEaREXtREd2CG413UcIfa4u8P/y08VgaCC+AhEhYATasLLPgpHlhLg8nm4HXpS
        8mz0Na3iIK2pzc0cX6+TihtojrR1we8lA7Ng85hYKpeV6F2qOBFhoW83HU5qcyrd
        3rAR3bmEqyROrORs7qVOvsN8MH98i4T3J4n1N6oXDVwCRAF3k3E8JvqsWMMahRK9
        xA8RkxmGq+E/0JcicmUbfjUnzkxLzhxTbktYIXGGQhYGKP27jQfSRVjygauXpmPy
        eRFFvQ44kVZAOEVD007olqWmO/nI1K0o8CLy/prnHGtDfD2FAoIBAQDAD+hHdIE1
        gids6+kNTR62uh7pMA7SvBPueFqpqdOwKMGjYxxrQ/rvKq5n2+UwGtGfGpUQnjoD
        /kDnu69Ne/oPKMdj7uOdg/eyOq7jpH50JwLEOqu1yRg9AKo7kqYmSvc3dSKg1+ag
        UM4TDpO9TXMKN2tYhUP5EMpUBhGdXDp4kX8W3WC5c9smEiYXDf2Cstz1VdtI3Txk
        /37YMLakoTe+LuL69StqOWs99GBaPCqajj9RzNpgzk1mHpWwBhf4FTGmfdMpmqAg
        68TAYJAqMHPGF/cQAiap3id7DX9U6O6gJQZfcOrS5M7Tu6XudDHrIlinzbwV8B4x
        TkiLVNuB1c5bAoIBAQDEnRl/k2XAGU1xm2sFgzbG4VItwpi8cTWsuUOFORmCKBvc
        nC3aYSPNeC92gpb7N6gMSdBJ3Zv3o75yPToev9L1hGZRserq46+Q03PnY8jrI/z+
        lCvLzQnkeuReFud3uXrcJprBdOEGWyTWmEi/m2ktJMbdSLjED/3i6w2aK2EMzxfN
        tvAIcRm20eq4oGrxTFCzGSt/5r6ueLY/0zV+7mka+FCidVDIGHomTQQFUH8qMPf0
        Hq9qgridTY8J9zDrXLFa3Jg1h1joVoJox4+fcvfltBACNHyr3VmDJxAp1Kvr2Taj
        +x/AYgr+vB500Yx0PtOzFzRiJQaMhFqvmWozwA/lAoIBAQC6f/fnQxug8QUFwMMq
        lmOnvm37tB4Axn94RsiLDg0wdzMpTDmxc269Ra3bzmzsXG6HWBG99FeTvxYZsGfX
        DvdQNyH/SV8feqFRIajoBriAY81M7UgGGwL9YaLsfEf40TzkTktU8rHRpQWm/bW6
        0fVOy2fiqm3J8mL2WnpKWt+wamCFvGyLSRRaEK+KHZy5iKQFW9y3EZXu4Sa0GgGR
        NbfiZrckSGRjHuSjYaUammgocs7LyOeZr1r7OeHS7ufhj/sJmA8vzCWIMkl5IYt8
        XFZf2q+fjOcsdjvSQtYNhq8JNUrN7OEp7uNkOUg0mAJNOKnsMFxe1S8MY98P5VPN
        7OcXAoIBAGfy/GJOlLgyzsqzQ8oVz5mIyxKKueEfpWfsfd2ql+qkfkO0k7bPqD0J
        bGB8H0wTrz9CV70EoLSoGewc2cr3ILcSVJEtveDixn+Mu1VIU+xXXn2Ox3kibvl3
        IvTEFMW92A4Rlt5sE6tiiu2i/RkCozFTZTeQaGL5pnd/FkhIElDHRwOrE2ZwRElh
        Iod+pwuXJtByucX3gteRbJ8rQGU/dLNqONHJXhlEVbaEjzG+vIDHl6bbVNyjZvjy
        qWH5z05p7FffTsS6kDCqv+dPz1QOtGJU8/bULADtHV233GDVjRiyih0lzOIQw2wO
        W9mwEikft2z3gegjHNo5H87+MgUYFMA=
        -----END PRIVATE KEY-----
    - app-id: wechat
      secret: a135ec07-6eb2-4300-840a-9977dd8c813c
      platform: 1
      wechat-app-id: "xxxx"
      wechat-secret: "xxxx"
      public-key: |-
        -----BEGIN PUBLIC KEY-----
        MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAuKVHWrfSoGr5eW9l2DZ8
        xsasUXRjgx0D7XGsVTdcE2W569KKySm/bY+hVFQ+A5MZJLbstYMYfvwJfpxW/dDe
        npvHQPlHXRvqTNVk9BVn4GZdIMjeN3yst5uDghVSOIMh6T0t7pbh1NA9QyQ9CtU4
        i5ntKP/O8vvKsSY4+OOAXM2ZbBB6mc3Nc7seYHitY0371eWx6neu1dRK4dyoZz+j
        9wdqAi4t+jwyz3qmYsaCXyIrdlgOlXYCM7Qw1RhaF4Lb3DmFqzLEFAEQMKaOEOpf
        viR5JeQ3ItFHWwOytOaahVEV2tU8LgE3ryJkrnESL+x4Ko5wPqLShiMNdRCAn52d
        nwJDbhn+wFqiturmvGcr0rKG6xxySOttNqJLAtrhY1XJQMR8xd+AHndwvpP3wDII
        o2x6MpYHf5aHoxq8WCsy9NVRECL9p2o0md93T0C+CG5rocvTHPIxJU2rW9g97qTY
        ErecCdCnwfMVcfceEIh3Ske1VGYkKub8+QhiH1GNgnxttukgNzNaDClrCVR1Ij19
        vCd3qWRNM0pZdwiMGI8q2U4MHmfEW8VWfiUK0QxZCH02yjI4JNzoy9cXgGCh//jb
        5XuYJFUJCEI7+CWs+F64R8kqPI3mr31jQ4HSkzMo3TuWUWTucgpB0iEuDsz9fp59
        zPoVuGG1cjnvzWGOKElJcxkCAwEAAQ==
        -----END PUBLIC KEY-----

      private-key: |-
        -----BEGIN PRIVATE KEY-----
        MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQC4pUdat9Kgavl5
        b2XYNnzGxqxRdGODHQPtcaxVN1wTZbnr0orJKb9tj6FUVD4Dkxkktuy1gxh+/Al+
        nFb90N6em8dA+UddG+pM1WT0FWfgZl0gyN43fKy3m4OCFVI4gyHpPS3uluHU0D1D
        JD0K1TiLme0o/87y+8qxJjj444BczZlsEHqZzc1zux5geK1jTfvV5bHqd67V1Erh
        3KhnP6P3B2oCLi36PDLPeqZixoJfIit2WA6VdgIztDDVGFoXgtvcOYWrMsQUARAw
        po4Q6l++JHkl5Dci0UdbA7K05pqFURXa1TwuATevImSucRIv7HgqjnA+otKGIw11
        EICfnZ2fAkNuGf7AWqK26ua8ZyvSsobrHHJI6202oksC2uFjVclAxHzF34Aed3C+
        k/fAMgijbHoylgd/loejGrxYKzL01VEQIv2najSZ33dPQL4Ibmuhy9Mc8jElTatb
        2D3upNgSt5wJ0KfB8xVx9x4QiHdKR7VUZiQq5vz5CGIfUY2CfG226SA3M1oMKWsJ
        VHUiPX28J3epZE0zSll3CIwYjyrZTgweZ8RbxVZ+JQrRDFkIfTbKMjgk3OjL1xeA
        YKH/+Nvle5gkVQkIQjv4Jaz4XrhHySo8jeavfWNDgdKTMyjdO5ZRZO5yCkHSIS4O
        zP1+nn3M+hW4YbVyOe/NYY4oSUlzGQIDAQABAoICAF/QpG5W5V2JJVv2iorf+2/K
        uLCsDNeEvvz/98VgrM8EAq502r/4gfWAit8Pt/5y3qFGqx6loJiEgQjKZ/nd4Se8
        /nCg6n9OdQ7ZzUE7umOfusPAeE+iyp2cfWmLVtcsdPRrYuJkOVwNkzy8GVD9xBHt
        FjwoQmOkdVHn27iLlZiSuAJzqqsVOH/Nob294XuehAhC4UgiQv+C4jjCIEEzrQoL
        Nt9ax1EK2/L+Wkj3ab+kI5mNqEO2sP3Ti2OI93cr2Js23j4wYb9frd8RDreIZ5Zr
        ptIa0uGmZ7i6+okVASodIZIlBM16pEKlPkmnMyDbPKAYufZG16fzmJAeuCAb0iZG
        yBvZHCjY2FP3+RFZq47F1ID4BLb2C9OgRkFyRmqAAbE4hdVEhzGx+qiDvk5du5iR
        REZUjzRLgkmMLNhaPztOZQCFc8a1uZtFhbycQc7mGkyEJJvhynl7A/gpv8kB3pcA
        Z/phJXdRa9b166Lr9sfFVzY8Cf6mBkUOZUs+3PsUD3o3By69McMO/7HN14m5FDpY
        QJTUoXTXe8Cf4DoqcTD2Zyw4qIY0nHRURKXDrmVwC+Vt/g6R9ayHX2muG8Rb0m6n
        2du9YMY7Xw/b+vwjLkXq39VIVikY2DuaoDOg+Veu4MkbRUqmYCTN8le/9MHetGkI
        rtU9F3t7orgvi4A4BEfhAoIBAQDr+J/GkY7y6XgkCU8usUmQIb/B4DOnCaMjQUGf
        rCTvBlWuAz8emSDAfl0wyIG4iuQftckIm/KRuzvc0e/N1lpDdWBCNN9HgbfEImWd
        dLuWpB/7X+NRQM/3IIRzAUK11Fy0ym1UyhKTq9zwV4gxfWGOUuZ5wuZ+NYJYeFIO
        9o5Np8p84CwOqO0fgT5iQPoXJmi2zyPr9iYvBGinosnav4blNy1x2pbrpLpR5YXZ
        rJpt/HVfr+KOK6Mh/XXGTd+wY2oVQZ5utY/5TQxxVPBbzwe5V9p7Ww4WI+pGD9IJ
        3/nlJoMCC4w171PhfrvtbPizlJopLUUNpA74Mb3v0hFK7kWPAoIBAQDIUWkVwpJi
        PBHKFDfIq9p7jtn2BM/fIuLWOWBzskl+dPuhxfav034oT3aoU8hKUsMeDzXBh6rt
        n73Ki0jQzwrW/VvZ4wHBf95Rw5VAxsb41OqrxFfAU42afbBzFpdTWI5VNX9EpPQI
        fVTwHOIh6Jj12qn/485vm3qgazRjOlGywjPqpM9uZhV1NOHorb8elohHzmwjUhob
        gik1ufVRB3Mc1OvnPmNfugIWhpiE9uo/RjbCAWO67J/oQo/zeaATTfJ//QHml9qY
        Q87lV6tI3rQJ/06PPMpNCo+2SDe6UeqQAS4beeNFwf+tp7FnNXR81vQWZ3j1qncq
        oYwGVSx3TnjXAoIBAHVbd4s4RVIGT1wMzTa5sY5fWpE/wjCnGF2mTM7uvIesLNyY
        fMHpAmL59bsXXXy8huxGaq8/cAqOhh0yxAMpQkcejzseNJXJq+199e+zaMBo7AcH
        D3UPuN59a6IO1HC+J0U7D9kFjuumpAFcZz3Fz8kK7dlM13mZfzQk0xriALAabRhi
        HUdFOHlcu/v9uOPelGGm74ShLShhFvOYgK+sZZiGMrHXNwwHJysn7cPulfdxgaaP
        QSvYBBAZkIOJo2CEcPQVaIhDAFHKwg9zYP8oHf1N9jk3dfAI+LDTmXCT1iLjXnCb
        8aW5W4xgjXJtqdsWYv1rqFY6a7+AbahiX3tWuX0CggEAYHMqWMrVdq0bl6QCdAGi
        8ekHMzh/6h0/AQyhTzOhxVyIKA1MSL5ZOQmBxWyJvJd60Qdbx7IN79oBJPvJdJir
        zHYy+ocdulBZ+B5mx8it1vOVhlzEL5tLS/6GrfNLq1qxNX/Lpn6R7WCDPBV8H/2B
        YKcHQWkrZXuEIKddkwVqftqY6rquEabfYA61UzYNFqo+NezDDoKihWo3c2H1Jy2i
        FFjEuRPF/zptdPEbkLHeedbR2LmYjlEOcWNTMlT2aTUXtN5aQvAM1VGY1b5Pf4eT
        QlkGN1t6wHt8VLUS+AgnG20mCR63+kd9VtyuQ1ZunwlUf1EU4ZxRQlqENCxge5Vy
        AwKCAQEAof5HOqfE4vNSCG1+HMjisNHij7gZZRAKzhhk6eZxsxphCVSM5gTszu4s
        FemoE7juESxvIHLpAQT6Cdav6zFh4jL0fVBiweYTvXoH+cT8brf7BmQub1J7HAwy
        dPUUXoyGsc9/BcZwCgPdGPxYCQ7SmzkRsdXxZhZE8K0U57T9sOSwPoyVap+V5cdp
        lI04gQrgNGxplgXj4u8BwtJFCDWqKNQXg/xK6uMiLsBbFkicTxhBrx/qe+vp8MRJ
        KG8mh2BHsoFS3oIsT3S96NbD7BgagNym8kZBfWPekznh7/CvzggwQ2Qz/8QqzBTE
        vf7k9NYvSYtv7Yw1BgH8mt8xbf7dgw==
        -----END PRIVATE KEY-----
  cache:
    - cache-name: user
      ttl: 1800000
      max-idle-time: 1200000
    - cache-name: action
      ttl: 1800000
      max-idle-time: 1200000