spring:
  datasource:
    url: jdbc:mysql://192.168.100.80:3306/app?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      pool-name: vcloud
      maximum-pool-size: 25
      max-lifetime: 1500000
      validation-timeout: 1000
      idle-timeout: 60000
      minimum-idle: 20
  redis:
    host: 192.168.100.80
    port: 6379
    connect-timeout: 1000
    timeout: 1000
    lettuce:
      pool:
        min-idle: 5
        max-active: 8
  jpa:
    open-in-view: false
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
    clean-disabled: true
  jackson:
    default-property-inclusion: non_empty
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    sentinel:
      enabled: true
      transport:
        port: 8719
        dashboard: 192.168.100.80:8080

logging:
  config: classpath:logback.xml

mybatis-plus:
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mybatis/**/*.xml
  type-enums-package: com.bootvue.datasource.type

knife4j:
  enable: true
  setting:
    enableDynamicParameter: true
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: MIT License | Copyright 2020-[vbeats](https://github.com/vbeats)
    enableOpenApi: true
    enableHomeCustom: true
    homeCustomLocation: classpath:swagger.md

# 自定义配置
vcloud:
  skip-urls:
    - /auth/**
    - /swagger/**
    - /**/api-docs
  caches:
    - cache-name: admin
      ttl: 1800000
      max-idle-time: 1200000