spring:
  datasource:
    url: jdbc:mysql://192.168.100.80:3306/app?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      pool-name: vcloud
      maximum-pool-size: 25
      max-lifetime: 1500000
      validation-timeout: 1000
      idle-timeout: 60000
      minimum-idle: 20
  redis:
    host: 192.168.100.80
    port: 6379
    connect-timeout: 1000
    timeout: 1000
    lettuce:
      pool:
        min-idle: 5
        max-active: 8
  jpa:
    open-in-view: false
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
    clean-disabled: true
  jackson:
    default-property-inclusion: non_empty
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    sentinel:
      enabled: true
      transport:
        port: 8719
        dashboard: 192.168.100.80:8080

logging:
  config: classpath:logback.xml

mybatis-plus:
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mybatis/**/*.xml
  type-enums-package: com.bootvue.core.constant

knife4j:
  enable: true
  setting:
    enableDynamicParameter: true
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: MIT License | Copyright 2020-[vbeats](https://github.com/vbeats)
    enableOpenApi: true
    enableHomeCustom: true
    homeCustomLocation: classpath:swagger.md

# 自定义配置
vcloud:
  wechat-app-id: "xxxx"
  wechat-secret: "xxxx"
  skip-urls:
    - /auth/**
    - /swagger/**
    - /**/api-docs
  keys:
    - app-id: web
      secret: 6842224b-7ddb-4c63-af62-1db58d77b2a5
      platform: 0
      public-key: |-
        -----BEGIN PUBLIC KEY-----
        MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEArzmOBJ48DcLBUQjzUaNf
        NVik73tueZudyhmYw2fhHuPIAdLwrJiC0JDNjeAXaguWXbwKtYXKursVRaOCU/4V
        kBE/Ld7LbRDTRzajtn+dE2NDcWxDTYQlqdRL8Om5HNyztfc9G4WhyMR5CrMraSwl
        BJgCoPkIFDiZJA00fbD/Bv8IJkjpy1Zk+r6bEEdp2oVpB8giTPspznS9bkeHifRI
        TX7FEh5dAaNcj6l85G78ixZyP7Uxy019u1yjNiSw34Mn7MUYnhhy+dR2hG4F6loW
        rU6JbGYt/AiJBLQ2XNNbiUAVUAzyzclMn+fHkY9a52jsM0UxKT5KN0CmccpLLb18
        tdx8ZskeufQMY+FfoWIN1Ia8J/gslq0VzzIJVlvJPaoZd29Spd2VjSk+8v4zElUV
        vJnmIRd0z9qp4vEht2WgLUn4o55owyB0Lib8wwgXovEQFYSQ0jlJQ7S+eJkrIjcB
        jsfR/o1sHZINeA+TNf97k7UMQirBu2s83SkBwWX9QHnpgUZkMBHwIkngAjLmF5Zn
        szVZYA0pCdwjjpGtRyKgKaDLmbl2f22us7qG/p4cxWGsFjWcpyxaBryetP4gkI/r
        99BlflAyknq3hy3VaW2YQCesB+w3d8B1FQFXuIdgccz0yMKIXP/Zhnsr7vKMw2SN
        DzxI1g9fjJeWK1HIjR75lR8CAwEAAQ==
        -----END PUBLIC KEY-----
      private-key: |-
        -----BEGIN PRIVATE KEY-----
        MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQCvOY4EnjwNwsFR
        CPNRo181WKTve255m53KGZjDZ+Ee48gB0vCsmILQkM2N4BdqC5ZdvAq1hcq6uxVF
        o4JT/hWQET8t3sttENNHNqO2f50TY0NxbENNhCWp1Evw6bkc3LO19z0bhaHIxHkK
        sytpLCUEmAKg+QgUOJkkDTR9sP8G/wgmSOnLVmT6vpsQR2nahWkHyCJM+ynOdL1u
        R4eJ9EhNfsUSHl0Bo1yPqXzkbvyLFnI/tTHLTX27XKM2JLDfgyfsxRieGHL51HaE
        bgXqWhatTolsZi38CIkEtDZc01uJQBVQDPLNyUyf58eRj1rnaOwzRTEpPko3QKZx
        ykstvXy13HxmyR659Axj4V+hYg3Uhrwn+CyWrRXPMglWW8k9qhl3b1Kl3ZWNKT7y
        /jMSVRW8meYhF3TP2qni8SG3ZaAtSfijnmjDIHQuJvzDCBei8RAVhJDSOUlDtL54
        mSsiNwGOx9H+jWwdkg14D5M1/3uTtQxCKsG7azzdKQHBZf1AeemBRmQwEfAiSeAC
        MuYXlmezNVlgDSkJ3COOka1HIqApoMuZuXZ/ba6zuob+nhzFYawWNZynLFoGvJ60
        /iCQj+v30GV+UDKSereHLdVpbZhAJ6wH7Dd3wHUVAVe4h2BxzPTIwohc/9mGeyvu
        8ozDZI0PPEjWD1+Ml5YrUciNHvmVHwIDAQABAoICAQCC3PgcqNRu7oGT9JxL3zhu
        zeo4VLW4KqlYU2+MmFs/x5wLCK/oJuqju1FY4QB7mXXOQW66DNbQSIJlhO0Dr6II
        +2h06IyCwusXp03zMTFtVlf7MIC/Nq8uO7gPj25JiObKQoCnulCOcXV4sUD9hhOL
        b7+e2v3WpEJy8029hV+hqPw8I34/9yDpR0rliIAczEAZqLU9SuL5JqSG5PLr673H
        6qJhmr2ZSJkLTehRbjY75iKjQ76ReCkrsc7O0+4or3o00SpGgDn2LV/qHYVbdbaz
        7hCiHVnAfdte4PwsrUkSowKHy3PWjr0kO2UHZ8nbQ7gLvmQtyjCBPU5Rc2RcH8Uv
        jJMyUG2XVDrJh+b9jblE4lkEDy4NosfIfmdWEbO3ZQBHqMD0J9AVjvuP3ay9+/EF
        LEMOz5OWNRmfpaY1PIEEtUnnZSlFJiLe0AzpikZZDj18oUYUyh7l1oso1SIBdFzS
        5eOvCh6NKZSadxRISHUs9oGcdrP5jhrf+pjt/SqgsRdHBFNEeu8IPxwZDKQZMgub
        rq+UaBqHowCCOa+Fg38hUT7Z0fvd/PMFMtKvAHQvnwlCgHy7SMcDAqg/5stltdZn
        8eg300Wru1azb8Km2dI+abZCRgdgftZkwWnFYej5s9HNLlXC5y888BFfeql3iJpj
        BCR9RInacPjkkrKwuCfgGQKCAQEA22EHM+VlhWg8FRA9FJgiPPGJ0jlrCW3sSJ6j
        /XvtitwbLpzVuYso6FkDoI7VEe3S5VnvReMKlvZhQHjlQDg03WGYq55qPtzpN/8k
        hn0cPPHZsFJ+StzGwBZ2BOdBbfUcSb3rzJCk/3+qfOP261xlmX0JdatsxbFA1+HT
        3VaMhVtBv1dPrztjhdl3VMJ0RSCiSMHW9lBuqBvRbkB0xa3zkHiCGcNIoGLL1RuS
        D+vDWVXbBrW9OWQyKmn2kx/ak0SnHxX5XHFcesAbHXxGbTyN37OSfxfpafC17XA7
        UsplnX1PhQavlObAr7+GBlYlKzHyiDdO6NUf/Yoj9rzOaQsOHQKCAQEAzHmisL3K
        Ozc5V6OTyl9FTMypJDUkWAMbj5NlnivKhOi9eXuJbslS8M9t+H0KHxu1us1L6NpX
        y24QfkFWu2atafoTeTpmm9li83V4RCBlQfEUp6lQhnuCihZz0J/Vz2Q/eMmX4fu6
        +fhG+KgwUePUOb8AQnoonxwZUJd5o5LoIoUtmuyXK4CLlKcCU0cQZVpOB2lvQ2zA
        mk8l0rIferrL5rNTSZQdT2QnLIQ7iSiqRWw/iUQGo+GC8qW0yzwP+ATUeEyAuTVt
        9Z5bAVeBwzmpRlHIajY3ZyvOzfNeSQJBXRKjMTiCNxwHcctdO5A9QLcnG+oleojR
        kHaVgi7sFGI7awKCAQAM0TVvhcaRrc5c2K8I5f6SGvaXbr1fNqnocERaigQN6eA4
        r/cYuRWxxYmdttqiCogY2FFPfv1eZpS2BJo4T1BfYtVdqYrBk3yYxfJnXSXqNaMn
        VxqD2zRNgsJwdOZwuzJk6JC/SfAp8VaPp24EwEg7WH/V/ScEwd9s/Ye4Vdct72/+
        8uX38ftVlagQLrBGXaq9n32ktHxSnBV3YJKx/gDN/wxy3uL+Y+dO0yaMgZTPQmHi
        mXmtwbngmoJKhEDr+8Xb3hfMm97wWQr8hQdEWJZdbItxm38KroKilb0RkDuxoOGl
        fweBJp45ZnI5Ko1PYcKuzLRyjAkrcge54bwZjQjNAoIBADNweiwqYsDI4MUaYqir
        lPyAFCEGuXDmvz08YHkNHTKYdmokWOuk/BeWp1y24B/5UZt/4BPhMer8cmvAtjgI
        2aFqhxGdTojwhEMpDytcVvzi0EZpgteCJNHmWhZmz1wQJSOW232/XUdbXUda0GUZ
        gp9QXJlcr/FvGTM8GB69a2abyGBMGq+X9AVeimg23XoR4MVekd4NctqfBK3fn6m5
        amhMPqyo9UKuuGgrj+qubz9tvwIiOeVqaw3t//CM2JuVY3osDMoLFfGPd+d7gyqA
        zAPjuR53KzLqQ2luSw7k4VqvwJw2UhPZGkpXVcoRPEeWi+Eq42jTGJ1WJ8CLW1q5
        Z6cCggEAWX1bXjj4NPvdtIFodrtJwRr1M6Plic1HUC5iwQIdOGmEc8Tarqebsen9
        yHeQ1FZtFyPAKOQWNKUGvEBx+ztu+z5OxHoFzC+rm/ThG1nvQMZV8BwdD3ueoBbK
        3suQmwp8ld0O6RNHY/mPe6chSWoA63qoat5PbBfDUuJl2zq29QXkJKoHK0dvf1kS
        x7XREQ28eubVvW3mhTBfu75F0PJBkwZgN4mI8kPVbx5kVe2lLpCCv+lf+b8x5EKU
        d0wdwbRhdJG8eKzHegHNZJ/ocQazr3XF2aShZViwLUqypEPpJWum1a6aOQgLWuVT
        tbfCf5UOvi5451HD+A/yG2HOShMGjA==
        -----END PRIVATE KEY-----
    - app-id: wechat
      secret: a135ec07-6eb2-4300-840a-9977dd8c813c
      platform: 1
      public-key: |-
        -----BEGIN PUBLIC KEY-----
        MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAsbWw4w4OlJ/J01xQd06t
        wRcvGlkHvEbq2bOU/OTBaHjyUNkiq4N3xrj7SfEedwXN8E7yKR+R1cQPy12Joh1r
        0zL9B3vaYmKgBNzdRADCDclVsdco66/2DHmXvDeVkuty6P4TLYGs64gQ60vKT/Fx
        ebupozHh95LuK2r27oy7riIHjcXBEb9lBJ2B/spLJHiJORQWI/a4dAaR6w7e0gas
        2QVCArPJxdCRgGdWsOxst9JkoR3ZJpeCXPi12lHgxbnFZ5yC624wKc2NCu631zYQ
        wb5xh+d2eaTU9vLzOqWWOljWE/blwnPEP0HJnc5lyPFqK2NlrWZCo1mZe41VTbwr
        3kFWbIjuQ8IPee/NyHcW3Az+7l9LUPPe7W3JsFrlPNr9KJm1jgdD9eLp/rMr+h67
        +M6hq8O+2B9SNh19wrECOQwjn8lhE65hFonWqrwJBX0PCRLVREK13JpO4WZkLgDL
        TlSohIEYZQPlwASi+I2U/Irrg96AZx7cNRDr9lVFeUpc0a9ToLl9jQex7WFIcQjL
        NWdOmfBCVIASAesJIFb4N+0DmzBwkEoCL8Ta0x+u0LDBRn6l8xd8gagLS8rqXTZ9
        +W3ueuTtOKjA75ZqGxL5G2pk09WN8zAOKGVY56oHXRIl+yoMfklBgjNwb9sAloFk
        FHi94OyisrZ4Wh3IqZiBxp0CAwEAAQ==
        -----END PUBLIC KEY-----
      private-key: |-
        -----BEGIN PRIVATE KEY-----
        MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQCxtbDjDg6Un8nT
        XFB3Tq3BFy8aWQe8RurZs5T85MFoePJQ2SKrg3fGuPtJ8R53Bc3wTvIpH5HVxA/L
        XYmiHWvTMv0He9piYqAE3N1EAMINyVWx1yjrr/YMeZe8N5WS63Lo/hMtgazriBDr
        S8pP8XF5u6mjMeH3ku4ravbujLuuIgeNxcERv2UEnYH+ykskeIk5FBYj9rh0BpHr
        Dt7SBqzZBUICs8nF0JGAZ1aw7Gy30mShHdkml4Jc+LXaUeDFucVnnILrbjApzY0K
        7rfXNhDBvnGH53Z5pNT28vM6pZY6WNYT9uXCc8Q/QcmdzmXI8WorY2WtZkKjWZl7
        jVVNvCveQVZsiO5Dwg95783IdxbcDP7uX0tQ897tbcmwWuU82v0ombWOB0P14un+
        syv6Hrv4zqGrw77YH1I2HX3CsQI5DCOfyWETrmEWidaqvAkFfQ8JEtVEQrXcmk7h
        ZmQuAMtOVKiEgRhlA+XABKL4jZT8iuuD3oBnHtw1EOv2VUV5SlzRr1OguX2NB7Ht
        YUhxCMs1Z06Z8EJUgBIB6wkgVvg37QObMHCQSgIvxNrTH67QsMFGfqXzF3yBqAtL
        yupdNn35be565O04qMDvlmobEvkbamTT1Y3zMA4oZVjnqgddEiX7Kgx+SUGCM3Bv
        2wCWgWQUeL3g7KKytnhaHcipmIHGnQIDAQABAoICAHT94VLJaU3tGAieqJay5G7P
        HYJiBFat9WSW9km7K5zkqtoQ6OMzLMJV+5EFPQIsfxRqVMA/+Vlatu8ySC7C4b5r
        veqUXgQRW7l30e839Ijw+AqZVGY9NGWoEv2lNkI/4SmEQwndagKxVDojbjBNCmCS
        7C305AeB4mwRAjmvysrruj9aZi2R7CYqr28WrHt5IxXBpIXOokY4IQ43fveTz20c
        KgXvaLFjCrcW0RquuzAVQYxUQyZF7lvYnJf6+VgSYeRBRGtL4kdS/DyrRbpX7JYw
        EzveZL/WhSGCdiAw7QLCg0UncMEgR51BaUMLozSzwiqISGLshIhXr1SIihUgAVw6
        b+6hFsYqVMGLoSU1YEydv6g/nrJijDGM2KjkNJXJLq1xxL2XeOlC2iLLgiRtn/8u
        6wdNwRICS+xCmyjsMwmwS9KV0gKPo0Ya5jUVLsiQ7MpHUjDg+fDCINHokEB9HNxu
        dB5oEgIVRZp365JvEehPajtmJTVk4oEkel+BLBM5aYWgbvwM5atlkvEGMAa7Pbxv
        v+Y0XV/4QTujmfPLxM6p9KdNwI3OC4mGICUyVhTleUpujB4GdrEf+zUN5pOA0k0+
        UvibEM2AtSvRpwLPmzvAEIVqb1ubaUNUKXRpFjiMqwjIG4zIxbMOlTQegPk5nDXZ
        jyJMc6SWKgXQIhl9GlWhAoIBAQDdJDf2bz5v73oeZopOC3kbx5vn3KEwvWg1iwNp
        mnDWBvrwb3G74BgbWGCMfslynke1L/51LFkolLj9KvzFITE/deefzdSRqDIFgx8H
        km6CbzpGjZDN9YLvR2PmlPEB++SIlDTIr1M6g7/ac/8YhUttCcd0CT/9Zg/8cBVs
        fpqPPeQLXX6RbBcQt7WSreyaFydD2DrI4ZwNo2YT53QqLRNucL7phREqxkIPNemx
        S6LG7/C4zvpH11Te5CS62jdtDVta+mnbvTD1R/EtW7+aTlzNdToCgjI+lTv66NuW
        RvZ/o2B/oboTAQWXhO4Ct87c3ZURR8AJaR2iJWAivk+mRBE1AoIBAQDNuNv/RC7R
        pddus6GjUZFXfu1pavXXUzf4s7J8N0IPuONCOFe8HgfllX0OZagOKgpefZ6okCjZ
        W6X4HZaU+8Lu/quppVRbLE/t/myTWWqUm5mJ1AhVYE59LwrnV4Sj1IA/YygEsFRk
        7MfFFq/FgWGKeR40DURGgTv+xrMortNCNbl3t8H/ziZP8SduDDodL7kFFj/lCb7d
        AImSeMMGxi36P87Y31v6+n8nK+J9+py8UBAYz21UUEZ0t7Ej3wimsE0XFnad6e87
        +u8SyMdQi2VZFcGYxkjElhscF+JWfNOQp8xpQOyX4OY/P9Lfy6f+94KLWOOdcQ3h
        WJJnpbpK+7TJAoIBAQC+pd7pQfaeIeMyGkzaA+IhJPEv73G3x1Lz9ii2/kKRAeuN
        JUb0JboiuQpjlVquye4gMoQ5GEa1SaJCALFyca83erp5dsXv3QVi4yv5JzDGmoWv
        FZTlOufqya1CuN0eTL81UDBBY4VpSPQ5rQ8bYK8qDeg6DU9xcnANvcN6iZtOKplT
        gwL+9CTecMLE9dSo85USVHQ5guc6isgSGNR5F+tMpz6vq9yk988ztdMG2qI2x9zM
        NwRmsymkDyPrQv3Nslo0EPb6ThzLGX6/D/4bVbuEFbAxQXV3psjTA7Vr1TnlyEAF
        SLRWdecQPbXD+hsJJq7A+w6ADnNRus8qpM+eE8iRAoIBAH3szh1u6wnBbiGBK0wB
        PepE86Y3psxrUDOYK4UFfhaJofKC8pFgAI1z99y8NSaWbUpxspCTza1fADTkR6xi
        f2wzz3hEj2JPuY2A041OioL0zAMmGwPHs8PE6/O4CqUOCoLCe1iDZuVwWsg1ntpS
        3BYbFXXfOQ+/Q64sirY4bXB12lWB0ep3kdQVVYFzUo9TCvomKG5WjNJS5eMWsKqQ
        3Mv2CvONpYv3kaW0oytiIFbU20WUkuOtT7NaTcAbYfxGpqmfQnRfIeWhMH5bEEYp
        TZw+SQbvONO83lNP+2fdeNNvIxy6dRhyvf2xX69Fxku3zdzmSE2zSj/KK7PuKh6D
        /KECggEBAKZvby/5rmPvcdwR2vStD6Ifk7jTUZAD2AxAIgtxiM+6BUFcUY/thEN9
        NAakKW8wS3sa6H5PvVsBWeVRj18CYEriD333vrjvsvEDBsi4TA+30z3Q6VD+4Jo6
        fLoBSi4rzVSsY0I0RTGb1BhPKkTofKQdlyYmGlGdqAqC9q1ESMqhdOOvl7P3vXKs
        UAE4v61Sudg/chJinLlmRzw5IShKnd2bPvlUHwUukb8puoYufCkWDXqO0ufPKlET
        lnWTvbfqyfhaca003btLZguJI/EM742F/sJrEBiDf+tp9ioquBB1RgckQJVJcZms
        50VUGnoEy7ECrbiLHC2t2Z54R4yyJRA=
        -----END PRIVATE KEY-----
  caches:
    - cache-name: admin
      ttl: 1800000
      max-idle-time: 1200000
    - cache-name: wechat-user
      ttl: 1800000
      max-idle-time: 1200000