spring:
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
    clean-disabled: true
  datasource:
    url: jdbc:mysql://192.168.100.80:3306/app?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      pool-name: app-pool
      maximum-pool-size: 25
      max-lifetime: 150000
      validation-timeout: 1000
  redis:
    host: 192.168.100.80
    port: 6379
    timeout: 1000
    lettuce:
      pool:
        min-idle: 5
        max-active: 8