knife4j:
  enableAggregation: true
  cloud:
    enable: true
    routes:
      - name: 认证模块
        uri: 127.0.0.1:8081
        location: /auth/v3/api-docs
        servicePath: /auth
      - name: 后台管理
        uri: 127.0.0.1:8082
        location: /admin/v3/api-docs
        servicePath: /admin